/*
 * Copyright (c) 2013-2015 Netcrest Technologies, LLC. All rights reserved.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.netcrest.pado.temporal.gemfire.impl;

import java.io.DataInput;
import java.io.DataOutput;
import java.io.IOException;

import com.gemstone.gemfire.DataSerializable;
import com.gemstone.gemfire.DataSerializer;
import com.netcrest.pado.temporal.TemporalClientMetadata;

public class GemfireTemporalClientMetadata extends TemporalClientMetadata implements DataSerializable
{
	private static final long serialVersionUID = 1L;

	public GemfireTemporalClientMetadata()
	{
		super.temporalName = "gemfire";
	}

	public GemfireTemporalClientMetadata(String temporalName, String temporalKeyClassName,
			String temporalValueClassName, String temporalDataClassName)
	{
		super(temporalName, temporalKeyClassName, temporalValueClassName, temporalDataClassName);
	}

	/**
	 * Reads the state of this object from the given <code>DataInput</code>.
	 * 
	 * @gfcodegen This code is generated by gfcodegen.
	 */
	public void fromData(DataInput input) throws IOException, ClassNotFoundException
	{
		temporalName = DataSerializer.readString(input);
		temporalKeyClassName = DataSerializer.readString(input);
		temporalValueClassName = DataSerializer.readString(input);
		temporalDataClassName = DataSerializer.readString(input);
	}

	/**
	 * Writes the state of this object to the given <code>DataOutput</code>.
	 * 
	 * @gfcodegen This code is generated by gfcodegen.
	 */
	public void toData(DataOutput output) throws IOException
	{
		DataSerializer.writeString(temporalName, output);
		DataSerializer.writeString(temporalKeyClassName, output);
		DataSerializer.writeString(temporalValueClassName, output);
		DataSerializer.writeString(temporalDataClassName, output);
	}
}
