#!/bin/bash

# ========================================================================
# Copyright (c) 2013-2015 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

. ./setenv.sh > /dev/null 2>&1
. ./all_env.sh > /dev/null 2>&1
. ./argenv.sh > /dev/null 2>&1

GENERATED_SOURCE_DIR=$PADO_HOME/src/generated

if [ "$HELP" == "true" ]; then
   echo "Usage:"
   echo "Removes generated code from the following source directory:"
   echo "   $GENERATED_SOURCE_DIR"
   echo ""
   echo "   clean_generated_code [-?]"
   echo ""
   echo "   Default: clean_generated_code"
   echo ""
   exit
fi

#
# clean generated code
#

rm -rf $GENERATED_SOURCE_DIR/*
echo "All files removes in the directory:"
echo "   $GENERATED_SOURCE_DIR"
