#!/bin/bash

# ========================================================================
# Copyright (c) 2013-2015 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

. ./setenv.sh > /dev/null 2>&1

GENERATED_DIR=$PADO_HOME/src/generated
if [ ! -d $GENERATED_DIR ]; then
  mkdir -p $GENERATED_DIR
fi

pushd $GENERATED_DIR > /dev/null 2>&1 

JAVA_FILES=`find $GENERATED_DIR -name *.java`

javac -cp $CLASSPATH $JAVA_FILES
jar cvf $DROPIN_DIR/generated.jar .
echo "Jar created: $DROPIN_DIR/generated.jar"

popd > /dev/null 2>&1
