#!/bin/bash

# ========================================================================
# Copyright (c) 2013-2015 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

. ./setenv.sh > /dev/null 2>&1

export EXECUTABLE=$0

if [ "$HELP" == "true" ]; then
cat << EOF

NAME
   $EXECUTABLE - Compile the generated source code

SYNOPSIS
   $EXECUTABLE [-jar jar_name] [-?]

DESCRIPTION
   Compiles the generated source code and creates a jar file in the following directory:

   $DROPIN_DIR/

OPTIONS
   -jar jar_name
             The name of the jar to be generated. Default: generated.jar

DEFAULT
   $EXECUTABLE -jar generated.jar

EOF
exit
fi

GENERATED_DIR=$PADO_HOME/src/generated
if [ ! -d $GENERATED_DIR ]; then
  mkdir -p $GENERATED_DIR
fi

pushd $GENERATED_DIR > /dev/null 2>&1 

JAVA_FILES=`find $GENERATED_DIR -name *.java`

javac -cp $CLASSPATH $JAVA_FILES
if [ "$JAR_OPT" != "" ]; then
   JAR_NAME="$JAR_OPT"
else
   JAR_NAME="generated.jar"
fi
jar cvf $DROPIN_DIR/$JAR_NAME .
echo "Jar created: $DROPIN_DIR/$JAR_NAME"

popd > /dev/null 2>&1
