#!/bin/bash

# ========================================================================
# Copyright (c) 2013-2015 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

. ./setenv.sh > /dev/null 2>&1

export EXECUTABLE=$0

. ${GRIDS_DIR}/${GRID}/site_${SITE}.sh > /dev/null 2>&1

PADO_PROPERTIES="-Dpado.home.dir=$PADO_HOME -Dpado.server=false -Dpado.properties=$ETC_DIR/client/pado.properties -Dpado.csv.properties=$ETC_DIR/client/csv.properties"
pushd $PADO_HOME > /dev/null 2>&1 
$GF_JAVA -Xms1024m -Xmx1024m $JAVA_OPTS -Djava.awt.headless=true $SECURITY_PROPERTIES $PADO_PROPERTIES com.netcrest.pado.tools.hazelcast.HazelcastCsvFileImporter $*
popd > /dev/null 2>&1
