/*
 * Copyright (c) 2013-2015 Netcrest Technologies, LLC. All rights reserved.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.netcrest.pado.gemfire.security;

import java.util.Set;

import com.netcrest.pado.security.server.LdapUserPrincipal;
import java.io.DataInput;
import java.io.DataOutput;
import java.io.IOException;
import com.gemstone.gemfire.DataSerializable;
import com.gemstone.gemfire.DataSerializer;

/**
 * LdapUserPrincipal extends UserPrincipal and contains LDAP specific info.
 * 
 * @author dpark
 * 
 */
public class GemfireLdapUserPrincipal extends LdapUserPrincipal implements DataSerializable
{
	private static final long serialVersionUID = 1L;

	public GemfireLdapUserPrincipal()
	{
	}

	public GemfireLdapUserPrincipal(String domain, String username, String userDn, Set<String> memberOfSet)
	{
		super(domain, username, userDn, memberOfSet);
	}

	public GemfireLdapUserPrincipal(String username, Object token, String userDn, Set<String> memberOfSet)
	{
		super(null, username, userDn, memberOfSet);
	}

	/**
	 * Reads the state of this object from the given <code>DataInput</code>.
	 * @gfcodegen This code is generated by gfcodegen.
	 */
	public void fromData(DataInput input) throws IOException, ClassNotFoundException
	{
		userDn = DataSerializer.readString(input);
	}

	/**
	 * Writes the state of this object to the given <code>DataOutput</code>.
	 * @gfcodegen This code is generated by gfcodegen.
	 */
	public void toData(DataOutput output) throws IOException
	{
		DataSerializer.writeString(userDn, output);
	}
}
