#!/bin/bash

# ========================================================================
# Copyright (c) 2013-2015 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

. ./setenv.sh

HOST_NAME=`hostname`

if [ "$1" == "-?" ]; then
   echo "Usage:"
   echo "  delete_key [-alias <alias>] [-?]"
   echo ""
   echo "  Deletes the certificate of the specified alias from the following"
   echo "  private key store file:"
   echo "     $SERVER_KEYSTORE_FILE_PATH"
   echo "  And deletes the certificate rom the following trusted keystore files:"
   echo "     $TRUSTED_KEYSTORE_FILE_PATH"
   echo "     $PADO_KEYSTORE_FILE_PATH"
   echo ""
   echo "  -alias <alias>   Alias name used for key alias. Default: $HOST_NAME"
   echo ""
   echo "   Default: ./delete_trusted_keystore -alias $HOST_NAME"
   echo ""
   exit
elif [ "$1" == "-alias" ]; then
   ALIAS=$2
elif [ "$1" != "" ]; then
   echo "Invalid option: $1. Aborted."
   echo ""
   exit
fi

if [ "$ALIAS" == "" ]; then
   ALIAS=$HOST_NAME
fi

echo ""
echo "Deleting alias=$ALIAS from $SERVER_KEYSTORE_FILE_PATH..."
keytool -delete -keystore $SERVER_KEYSTORE_FILE_PATH -alias $ALIAS -storepass $SERVER_KEYSTORE_PASSWD
echo "Deleting alias=$ALIAS from $TRUSTED_KEYSTORE_FILE_PATH..."
keytool -delete -keystore $TRUSTED_KEYSTORE_FILE_PATH -alias $ALIAS -storepass $TRUSTED_KEYSTORE_PASSWD
echo "Deleting alias=$ALIAS from $PADO_KEYSTORE_FILE_PATH..."
keytool -delete -keystore $PADO_KEYSTORE_FILE_PATH -alias $ALIAS -storepass $PADO_KEYSTORE_PASSWD
echo ""
