#!/bin/sh

set -e

PADO_DIR=/apps/adf/pado/prod-iot 

if [ "$1" = "purge" ]; then
   # Remove the entire prod-iot directory
   rm -rf $PADO_DIR
fi

# Remove service files
if [ -e /etc/init.d/pado.server ]; then
   rm /etc/init.d/pado.server
fi
if [ -e /etc/init.d/pado.locator ]; then
   rm /etc/init.d/pado.locator
fi
