#!/bin/bash

# ========================================================================
# Copyright (c) 2013-2015 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

# This script generates DTD code for pado.dtd using JAXB. 
# Include the JAXB bin in PATH before running this script.
PATH=/home/dpark/Work/products/jaxb-ri-2.2.6/bin:$PATH
xjc.sh -d  ../../../../../pado-core/src/main/java -p com.netcrest.pado.internal.config.dtd.generated -dtd pado1_0.dtd 
