#!/bin/bash

# ========================================================================
# Copyright (c) 2013-2015 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

pushd .. > /dev/null 2>&1
. ./setenv.sh > /dev/null 2>&1
. ./all_env.sh > /dev/null 2>&1
. ./argenv.sh > /dev/null 2>&1
. ${GRIDS_DIR}/${GRID}/site_${SITE}.sh > /dev/null 2>&1
popd > /dev/null 2>&1

if [ "$1" == "-?" ]; then
   echo "Usage:"
   echo "   backup_diskstore [-site $SITES_OPT] [-dir <backup dir path>] [-?]"
   echo "   Default: backup_disk_store -site $SITE_DEFAULT -dir $DISK_STORE_BACKUP_DIR"
   echo ""
   exit
fi

LOCATORS=`getGemfireLocators`

# the parent directory of all servers, locators, and gfsh
if [ "$RUN_DIR" == "" ]; then
   RUN_DIR=$BASE_DIR/run
fi
GFSH_LOG_DIR=$RUN_DIR/gfsh
if [ ! -d $GFSH_LOG_DIR ]; then
  mkdir -p $GFSH_LOG_DIR
fi

if [ ! -d $DISK_STORE_BACKUP_DIR ]; then
  mkdir -p $DISK_STORE_BACKUP_DIR
fi

pushd $GFSH_LOG_DIR > /dev/null 2>&1
echo gfsh -e "connect --locator=$LOCATORS" -e "backup disk-store --dir=$DISK_STORE_BACKUP_DIR"
gfsh -e "connect --locator=$LOCATORS" -e "backup disk-store --dir=$DISK_STORE_BACKUP_DIR"
popd > /dev/null 2>&1
