#!/bin/bash

# ========================================================================
# Copyright (c) 2013-2016 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

pushd .. > /dev/null 2>&1
. ./setenv.sh > /dev/null 2>&1
. ./all_env.sh > /dev/null 2>&1
. ./argenv.sh > /dev/null 2>&1
. ${GRIDS_DIR}/${GRID}/site_${SITE}.sh > /dev/null 2>&1
popd > /dev/null 2>&1

# Check for script help
if [ "$1" == "-?" ]; then
        echo "Usage:"
        echo "   ./import_all [-grid $GRIDS_OPT] [-site $SITES_OPT] [-?]"
        echo "   Run import_csv on all servers. Before running this command, first place"
        echo "   all schema and data files in each server's data directory."
        echo ""
        echo "   Default: ./import_all -grid $GRID_DEFAULT -site $SITE_DEFAULT"
        echo ""
        exit
fi

pushd .. > /dev/null 2>&1
SERVER_HOSTS=`getServerHosts`
popd
COMMAND="cd $PADO_HOME/bin_sh/tools; ./import_all"
for i in $SERVER_HOSTS
do
        echo ssh -q -n $SSH_USER@$i -o stricthostkeychecking=no $COMMAND
        ssh -q -n $SSH_USER@$i -o stricthostkeychecking=no "$COMMAND" &
done

echo ""

