#!/bin/bash

# ========================================================================
# Copyright (c) 2013-2015 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

pushd .. > /dev/null 2>&1
. ./all_env.sh > /dev/null 2>&1
. ./setenv.sh > /dev/null 2>&1
popd > /dev/null 2>&1

PADO_PROPERTIES="-Dpado.home.dir=$PADO_HOME"
$GF_JAVA -Xmx256m -cp $CLASSPATH $PADO_PROPERTIES com.netcrest.pado.biz.file.FileSplitter $*
