/*
 * Copyright (c) 2013-2015 Netcrest Technologies, LLC. All rights reserved.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.netcrest.pado.gemfire.info;

import java.io.DataInput;
import java.io.DataOutput;
import java.io.IOException;

import com.gemstone.gemfire.DataSerializable;
import com.gemstone.gemfire.DataSerializer;
import com.gemstone.gemfire.cache.util.GatewayQueueAttributes;
import com.netcrest.pado.info.GatewayQueueAttributesInfo;

public class GemfireGatewayQueueAttributesInfo extends GatewayQueueAttributesInfo implements DataSerializable
{
	private static final long serialVersionUID = 1L;

	public GemfireGatewayQueueAttributesInfo()
	{
	}

	public GemfireGatewayQueueAttributesInfo(GatewayQueueAttributes attr)
	{
		alertThreshold = attr.getAlertThreshold();
		batchConflation = attr.getBatchConflation();
		batchSize = attr.getBatchSize();
		batchTimeInterval = attr.getBatchTimeInterval();
		diskStoreName = attr.getDiskStoreName();
		persistenceEanbled = attr.getEnablePersistence();
		maximumQueueMemory = attr.getMaximumQueueMemory();
	}

	/**
	 * Reads the state of this object from the given <code>DataInput</code>.
	 * 
	 * @gfcodegen This code is generated by gfcodegen.
	 */
	public void fromData(DataInput input) throws IOException, ClassNotFoundException
	{
		alertThreshold = DataSerializer.readPrimitiveInt(input);
		batchConflation = DataSerializer.readPrimitiveBoolean(input);
		batchSize = DataSerializer.readPrimitiveInt(input);
		batchTimeInterval = DataSerializer.readPrimitiveInt(input);
		diskStoreName = DataSerializer.readString(input);
		persistenceEanbled = DataSerializer.readPrimitiveBoolean(input);
		maximumQueueMemory = DataSerializer.readPrimitiveInt(input);
	}

	/**
	 * Writes the state of this object to the given <code>DataOutput</code>.
	 * 
	 * @gfcodegen This code is generated by gfcodegen.
	 */
	public void toData(DataOutput output) throws IOException
	{
		DataSerializer.writePrimitiveInt(alertThreshold, output);
		DataSerializer.writePrimitiveBoolean(batchConflation, output);
		DataSerializer.writePrimitiveInt(batchSize, output);
		DataSerializer.writePrimitiveInt(batchTimeInterval, output);
		DataSerializer.writeString(diskStoreName, output);
		DataSerializer.writePrimitiveBoolean(persistenceEanbled, output);
		DataSerializer.writePrimitiveInt(maximumQueueMemory, output);
	}
}