/*
 * Copyright (c) 2013-2015 Netcrest Technologies, LLC. All rights reserved.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.netcrest.pado.gemfire.info;

import java.io.DataInput;
import java.io.DataOutput;
import java.io.IOException;
import java.util.List;

import com.gemstone.gemfire.DataSerializable;
import com.gemstone.gemfire.DataSerializer;
import com.netcrest.pado.gemfire.util.DataSerializerEx;
import com.netcrest.pado.info.ConfigInfo;
import com.netcrest.pado.io.IObjectSerializer;

public class GemfireConfigInfo extends ConfigInfo implements DataSerializable
{
	private static final long serialVersionUID = 1L;

	private boolean isClientMultiuserAuthenticationEnabled;

	public GemfireConfigInfo()
	{
	}

	public boolean isClientMultiuserAuthenticationEnabled()
	{
		return isClientMultiuserAuthenticationEnabled;
	}

	public void setClientMultiuserAuthenticationEnabled(boolean isClientMultiuserAuthenticationEnabled)
	{
		this.isClientMultiuserAuthenticationEnabled = isClientMultiuserAuthenticationEnabled;
	}

	/**
	 * Reads the state of this object from the given <code>DataInput</code>.
	 * 
	 * @gfcodegen This code is generated by gfcodegen.
	 */
	public void fromData(DataInput input) throws IOException, ClassNotFoundException
	{
		xmlContent = DataSerializerEx.readUTF(input);
		clientIndexMatrixConnectionName = DataSerializerEx.readUTF(input);
		clientLocators = DataSerializerEx.readUTF(input);
		objectSerializerList = (List<IObjectSerializer>)DataSerializer.readObject(input);
		isClientMultiuserAuthenticationEnabled = DataSerializer.readPrimitiveBoolean(input);
		configProperties = DataSerializer.readProperties(input);
	}

	/**
	 * Writes the state of this object to the given <code>DataOutput</code>.
	 * 
	 * @gfcodegen This code is generated by gfcodegen.
	 */
	public void toData(DataOutput output) throws IOException
	{
		DataSerializerEx.writeUTF(xmlContent, output);
		DataSerializerEx.writeUTF(clientIndexMatrixConnectionName, output);
		DataSerializerEx.writeUTF(clientLocators, output);
		DataSerializer.writeObject(objectSerializerList, output);
		DataSerializer.writePrimitiveBoolean(isClientMultiuserAuthenticationEnabled, output);
		DataSerializer.writeProperties(configProperties, output);
	}
}
