/*
 * Copyright (c) 2013-2015 Netcrest Technologies, LLC. All rights reserved.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.netcrest.pado.gemfire.info;

import java.io.DataInput;
import java.io.DataOutput;
import java.io.File;
import java.io.IOException;
import java.util.Date;

import com.gemstone.gemfire.DataSerializable;
import com.gemstone.gemfire.DataSerializer;
import com.netcrest.pado.info.DumpInfo;

public class GemfireDumpInfo extends DumpInfo implements DataSerializable
{
	private static final long serialVersionUID = 1L;

	public GemfireDumpInfo() 
	{
		super((String)null, null, null, false);
	}
	
	public GemfireDumpInfo(DumpInfo parentDumpInfo, File file, Date date, boolean recursive)
	{
		super(parentDumpInfo, file, null, recursive);
	}

	public GemfireDumpInfo(String parentFullPath, File file, Date date, boolean recursive)
	{
		super(parentFullPath, file, date, recursive);
	}

	@Override
	protected DumpInfo createDumpInfo(DumpInfo parentDumpInfo, File file, Date date, boolean recursive)
	{
		return new GemfireDumpInfo(parentDumpInfo, file, date, recursive);
	}

	/**
	 * Reads the state of this object from the given <code>DataInput</code>.
	 * 
	 * @gfcodegen This code is generated by gfcodegen.
	 */
	public void fromData(DataInput input) throws IOException, ClassNotFoundException
	{
		name = DataSerializer.readString(input);
		fullPath = DataSerializer.readString(input);
		childList = DataSerializer.readObject(input);
		size = DataSerializer.readPrimitiveInt(input);
		fileSize = DataSerializer.readPrimitiveLong(input);
		date = DataSerializer.readDate(input);
	}

	/**
	 * Writes the state of this object to the given <code>DataOutput</code>.
	 * 
	 * @gfcodegen This code is generated by gfcodegen.
	 */
	public void toData(DataOutput output) throws IOException
	{
		DataSerializer.writeString(name, output);
		DataSerializer.writeString(fullPath, output);
		DataSerializer.writeObject(childList, output);
		DataSerializer.writePrimitiveInt(size, output);
		DataSerializer.writePrimitiveLong(fileSize, output);
		DataSerializer.writeDate(date, output);
	}
}
