#!/bin/bash

# ========================================================================
# Copyright (c) 2013-2015 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

. ./setenv.sh > /dev/null 2>&1
. ./all_env.sh > /dev/null 2>&1
. ./argenv.sh > /dev/null 2>&1

if [ "$HELP" == "true" ]; then
   echo "Usage:"
   echo "   ./check_grid [-grid $GRIDS_OPT] [-site $SITES_OPT] [-?]"
   echo ""
   echo "       Displays running status of all locators and servers of all sites"
   echo "       in the specified grid."
   echo ""
   echo "      -grid      Displays servers in the specified grid. Default: ${GRID_DEFAULT}"
   echo "      -site      Displays servers in the specified site. Default: ${SITE_DEFAULT}"
   echo ""
   echo "   Default: ./check_grid -grid $GRID_DEFAULT"
   echo ""
   exit
fi

echo "*****************************************************"
echo "Grid: $GRID"
echo "*****************************************************"
if [ "$SITE_SPECIFIED" == "true" ]; then
      echo "-------------------------------------------"
      echo "Site: $SITE";
      echo "-------------------------------------------"
   ./check_site -grid $GRID -site $SITE
else
   for i in $SITES; do
      echo "-------------------------------------------"
      echo "Site: $i";
      echo "-------------------------------------------"
      ./check_site -grid $GRID -site $i
   done
fi

disown -a -r

