#!/bin/bash

# ========================================================================
# Copyright (c) 2013-2015 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

. ./setenv.sh > /dev/null 2>&1
. ./all_env.sh > /dev/null 2>&1
. ./argenv.sh > /dev/null 2>&1

if [ "$HELP" == "true" ]; then
   echo "Usage:"
   echo "Removes local locator log, stats files and persistent files."
   echo "Do NOT run this command while locators are running."
   echo ""
   echo "   clean_locator_local [-num <locator number>] [-grid $GRIDS_OPT] [-site $SITES_OPT] [-?]"
   echo ""
   echo "      Cleans up locator directories by removing log, stats, other temporary files"
   echo "      from the specified grid and site."
   echo ""
   echo "      <locator number> Locator number 1-99 ($GRID-$SITE: `getLocatorNumberRange`)"
   echo "      -grid      Removes log and stats files generated in the specified grid"
   echo "                 Default: ${GRID_DEFAULT}"
   echo "      -site      Removes log and stats files generated in the specified site"
   echo "                 Default: ${SITE_DEFAULT}"
   echo ""
   echo "   Default: clean_locator_local -num 1 -grid $GRID_DEFAULT -site $SITE_DEFAULT"
   echo ""
   exit
fi

. ${GRIDS_DIR}/${GRID}/site_${SITE}.sh > /dev/null 2>&1

if [ "$RUN_DIR" == "" ]; then
   RUN_DIR=$BASE_DIR/run
fi

# 
# clean locators
#
if [ "$LOCATOR_ID" != "" ]; then
   $COMMAND_PREFIX rm -rf $RUN_DIR/${LOCATOR_ID}*
fi
