#!/bin/bash

# ========================================================================
# Copyright (c) 2013-2015 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

. ./setenv.sh > /dev/null 2>&1
. ./all_env.sh > /dev/null 2>&1
. ./argenv.sh > /dev/null 2>&1

if [ "$HELP" == "true" ]; then
   echo "Usage:"
   echo "   ./kill_locator_local [-num <locator number>] [-grid $GRIDS_OPT] [-site $SITES_OPT] [-?]"
   echo ""
   echo "   Kills locator in the specified site of the specified grid."
   echo ""
   echo "      <locator number> Locator number 1-99 ($GRID-$SITE: `getLocatorNumberRange`)"
   echo "      -grid      Kills the locator in the specified grid. Default: $GRID_DEFAULT"
   echo "      -site      Kills the locator in the specified site. Default: $SITE_DEFAULT"
   echo ""
   echo "   Default: ./kill_locator_local -num 1 -grid $GRID_DEFAULT -site $SITE_DEFAULT"
   echo ""
   exit
fi

. ${GRIDS_DIR}/${GRID}/site_${SITE}.sh > /dev/null 2>&1

# should be only 1 locator
locators=`$JAVA_HOME/bin/jps -v | grep "pado.home.dir=${PADO_HOME}" | grep "pado.vm.id=${LOCATOR_ID}" | grep java | awk '{print $1}'`
for j in $locators; do
   lpids="$j $lpids" 
done

# kill the pids
echo
if [ "$lpids" != "" ]; then
   ssh -q -n $SSH_USER@$i "kill -9 $lpids;" > /dev/null 2>&1
   echo "Killed locator: ${LOCATOR_ID} $lpids"
else
   echo "Kill canceled. Locator is not running. ${LOCATOR_ID}"
fi
echo

disown -a -r
                              
