#!/bin/bash

# ========================================================================
# Copyright (c) 2013-2017 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

. ./setenv.sh > /dev/null 2>&1
. ./all_env.sh > /dev/null 2>&1
. ./argenv.sh > /dev/null 2>&1

if [ "$HELP" == "true" ]; then
   echo "Usage:"
   echo "   ./kill_site_rpc [-grid $GRIDS_OPT] [-site $SITES_OPT] [-?]"
   echo ""
   echo "   Kills RPC agents in the specified site in the specified grid."
   echo ""
   echo "      -grid      Kills the specified grid. Default: ${GRID_DEFAULT}"
   echo "      -site      Kills the specified site. Default: ${SITE_DEFAULT}"
   echo ""
   echo "   Default: ./kill_site -grid $GRID_DEFAULT -site $SITE_DEFAULT"
   echo ""
   exit
fi

. ${GRIDS_DIR}/${GRID}/site_${SITE}.sh > /dev/null 2>&1

# 
# Kill RPC agents
#

# RpcArray elements:
#   array[0] ServerNumber
#   array[1] RpcHost
#   array[2] MqttUrl
#   array[3] DebugPort
#   array[4] JmxPort
#   array[5] IsRpcStart
setLineArray $GRIDS_DIR/$GRID/rpc_${SITE}.sh

for (( i = 1; i <= $LAST_SERVER_NUM; i++ ))
do
   line="${LineArray[$i]}"
   array=($line)
   SERVER_NUM=${array[0]}
   if [ "$SERVER_NUM" == "" ]; then
      continue;
   fi
   RPC_HOST=${array[1]}
   ssh -q -n $SSH_USER@$RPC_HOST "cd $REMOTE_BASE_DIR/bin_sh; $COMMAND_PREFIX ./kill_rpc_local -num $SERVER_NUM -grid $GRID -site $SITE;"
done
disown -a -r
