#!/bin/bash

# ========================================================================
# Copyright (c) 2013-2015 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

. ./setenv.sh > /dev/null 2>&1
. ./all_env.sh > /dev/null 2>&1
. ./argenv.sh > /dev/null 2>&1

if [ "$HELP" == "true" ]; then
   echo "Usage:"
   echo "   kill_server_local [-num <server number>] [-grid $GRIDS_OPT] [-site $SITES_OPT] [-?]"
   echo ""
   echo "   Kills a local server in the specified grid and site." 
   echo "   The kill command is faster than the stop command"
   echo "   but at the expense of possible loss or corruption"
   echo "   of data."
   echo ""
   echo "      <server number> Server number 1-99"
   echo "      -grid      Kills the server in the specified grid. Default: ${GRID_DEFAULT}"
   echo "      -site      Kills the server in the specified site. Default: ${SITE_DEFAULT}"
   echo ""
   echo "   Default: kill_server_local -num 1 -grid $GRID_DEFAULT -site $SITE_DEFAULT"
   echo ""
   exit
fi

. ${GRIDS_DIR}/${GRID}/site_${SITE}.sh > /dev/null 2>&1

# should be only 1 server
servers=`$JAVA_HOME/bin/jps -v | grep "pado.home.dir=${PADO_HOME}" | grep "pado.vm.id=${SERVER_ID}" | grep java | awk '{print $1}'`
for j in $servers; do
   spids="$j $spids" 
done

# kill the pids
echo
if [ "$spids" != "" ]; then
   ssh -q -n $SSH_USER@$i "kill -9 $spids;" > /dev/null 2>&1
   echo "Killed server: ${SERVER_ID} $spids"
else
   echo "Kill canceled. Server is not running: ${SERVER_ID}"
fi

echo
disown -a -r
