#!/bin/bash

# ========================================================================
# Copyright (c) 2013-2015 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

. ./setenv.sh > /dev/null 2>&1
. ./all_env.sh > /dev/null 2>&1
. ./argenv.sh > /dev/null 2>&1

if [ "$HELP" == "true" ]; then
   echo "Usage:"
   echo "   ./locate_server [-num <server number>] [-grid $GRIDS_OPT] [-site $SITES_OPT] [-?]"
   echo ""
   echo "  Locates the specified server in the specified grid and site."
   echo ""
   echo "      <server number> Server number 1-99"
   echo "      -grid      Locates the specified server number in"
   echo "                 the specified grid. Default: ${GRID_DEFAULT}"
   echo "      -site      Locates the specified server number in"
   echo "                 the specified site. Default: ${SITE_DEFAULT}"
   echo ""
   echo "   Default: ./locate_server -num 1 -grid $GRID_DEFAULT -site $SITE_DEFAULT"
   echo ""
   exit
fi

. ${GRIDS_DIR}/${GRID}/site_${SITE}.sh > /dev/null 2>&1

if [[ "$(isNumber $SERVER_NUM_NO_LEADING_ZERO)" == "false" ]]; then
   echo "Error: The specified server number $SERVER_NUM_NO_LEADING_ZERO is not a number. Aborted."
   echo ""; exit
elif [ "$SERVER_NUM_NO_LEADING_ZERO" -le "0" ] || [ "$SERVER_NUM_NO_LEADING_ZERO" -ge 100 ]; then
   echo "Error: Invalid server number $SERVER_NUM_NO_LEADING_ZERO. Valid range: [1, 99]. Aborted."
   echo ""; exit
fi

# ServerArray elements:
#   array[0] ServerNumber
#   array[1] ServerHost
#   array[2] ServerPort
#   array[3] DebugPort
#   array[4] JmxPort
setLineArray $GRIDS_DIR/$GRID/server_${SITE}.sh
line="${LineArray[$SERVER_NUM_NO_LEADING_ZERO]}"
array=($line)
SERVER_HOST=${array[1]}
if [ "$SERVER_HOST" == "" ]; then
   echo "Error: Undefined server number $SERVER_NUM_NO_LEADING_ZERO. Aborted."
   echo ""; exit
fi

if [ "$SERVER_HOST" == "localhost" ]; then
   SERVER_HOST=`hostname`
fi

# find the process running on the host
PID=`ssh -q -n $SSH_USER@$SERVER_HOST "ps -ewwwo pid,comm,args | grep pado.home.dir=${PADO_HOME} | grep ${SERVER_ID}" | grep java | awk '{print $1}'`
echo ""
echo "          Dir: $PADO_HOME"
echo "    Server ID: $SERVER_ID"
echo "         Grid: $GRID"
echo "         Site: $SITE"
echo "Server Number: $SERVER_NUM"
echo "         Host: $SERVER_HOST"
if [ "$PID" == "" ]; then
   echo "   Process ID: Not found"
else
   echo "   Process ID: $PID"
fi      
echo ""

disown -a -r

