#!/bin/bash

# ========================================================================
# Copyright (c) 2013-2015 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

. ./setenv.sh > /dev/null 2>&1
. ./all_env.sh > /dev/null 2>&1
. ./argenv.sh > /dev/null 2>&1

if [ "$HELP" == "true" ]; then
   echo "Usage:"
   echo "   ./locate_server [-num <server number>] [-grid $GRIDS_OPT] [-site $SITES_OPT] [-?]"
   echo ""
   echo "  Locates the specified locator in the specified grid and site."
   echo ""
   echo "      <server number> Server number 1-99 ($GRID-$SITE: `getLocatorNumberRange`)"
   echo "      -grid      Locates the specified server number in"
   echo "                 the specified grid. Default: ${GRID_DEFAULT}"
   echo "      -site      Locates the specified server number in"
   echo "                 the specified site. Default: ${SITE_DEFAULT}"
   echo ""
   echo "   Default: ./locate_server -num 1 -grid $GRID_DEFAULT -site $SITE_DEFAULT"
   echo ""
   exit
fi

. ${GRIDS_DIR}/${GRID}/site_${SITE}.sh > /dev/null 2>&1

LOCATOR_COUNT=`getLocatorCount`
if [[ "$SERVER_NUM_NO_LEADING_ZERO" -lt "1" || "$SERVER_NUM_NO_LEADING_ZERO" -gt "$LOCATOR_COUNT" ]]; then
   echo "" 	
   echo "Locator number out of range."
   echo "" 	
   exit
fi

# LocatorArray elements:
#    array[0] LocatorNumber
#    array[1] LocatorHost
#    array[2] LocatorPort
#    array[3] JmxRmiPort
#    array[4] JmxHttpPort
setLineArray $GRIDS_DIR/$GRID/locator_${SITE}.sh
line="${LineArray[$SERVER_NUM_NO_LEADING_ZERO]}"
array=($line)
LOCATOR_HOST=${array[1]}
if [ "$LOCATOR_HOST" == "localhost" ]; then
   LOCATOR_HOST=`hostname`
fi

# find the process running on the host
PID=`ssh -q -n $SSH_USER@$LOCATOR_HOST "ps -ewwwo pid,comm,args | grep pado.home.dir=${PADO_HOME} | grep ${LOCATOR_ID}" | grep java | awk '{print $1}'`
echo ""
echo "           Dir: $PADO_HOME"
echo "    Locator ID: $LOCATOR_ID"
echo "          Grid: $GRID"
echo "          Site: $SITE"
echo "Locator Number: $SERVER_NUM"
echo "          Host: $LOCATOR_HOST"
if [ "$PID" == "" ]; then
   echo "    Process ID: Not found"
else
   echo "    Process ID: $PID"
fi      
echo ""

disown -a -r

