#!/bin/bash

# ========================================================================
# Copyright (c) 2013-2015 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

. ./setenv.sh > /dev/null 2>&1
. ./all_env.sh > /dev/null 2>&1
. ./argenv.sh > /dev/null 2>&1

if [ "$HELP" == "true" ]; then
   echo "Usage:"
   echo "   restart_server [-num <server number>] [-grid $GRIDS_OPT] [-site $SITES_OPT] [-gateway [<xml-file-path>]] [-rebalance] [-kill] [-?]"
   echo ""
   echo "  Restarts a server by first stopping or killing the running server in the"
   echo "  specified grid and site."
   echo ""
   echo "      <server number> Server number 1-99"
   echo "      -grid      Restarts the server in the specified grid. Default: ${GRID_DEFAULT}"
   echo "      -site      Restarts the server in the specified site. Default: ${SITE_DEFAULT}"
   echo "      -kill      Kills servers/locators before restarting them."
   echo "                 The kill command is faster than the stop command"
   echo "                 but at the expense of possible loss or corruption"
   echo "                 of data. This command removes all server persistent"
   echo "                 files if any."
   echo ""
   echo "   Default: ./restart_server -num 1 -grid $GRID_DEFAULT -site $SITE_DEFAULT"
   echo ""
   exit
fi

. ${GRIDS_DIR}/${GRID}/site_${SITE}.sh > /dev/null 2>&1

#
# Target host
#
# ServerArray elements:
#   array[0] ServerNumber
#   array[1] ServerHost
#   array[2] ServerPort
#   array[3] DebugPort
#   array[4] JmxPort
#   array[5] IsGateWay
setLineArray $GRIDS_DIR/$GRID/server_${SITE}.sh
line="${LineArray[$SERVER_NUM_NO_LEADING_ZERO]}"
array=($line)
SERVER_ADDRESS=${array[1]}

if [ "$SERVER_ADDRESS" == "" ]; then
   echo "Invalid server number. Please enter the server number and its host address in"
   echo "   ${GRIDS_DIR}/${GRID}/server_${SITE}.sh"
   echo ""
else
   if [ "$KILL" == "true" ]; then
      $BASE_DIR/bin_sh/kill_server $*;$BASE_DIR/bin_sh/clean_server $* -persist;sleep 3;$BASE_DIR/bin_sh/start_server $*
   else
      $BASE_DIR/bin_sh/stop_server $*;$BASE_DIR/bin_sh/clean_server -pidonly $*;$BASE_DIR/bin_sh/start_server $*
   fi
fi

