#!/bin/bash

# ========================================================================
# Copyright (c) 2013-2015 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

. ./setenv.sh > /dev/null 2>&1
. ./all_env.sh > /dev/null 2>&1
. ./argenv.sh > /dev/null 2>&1

if [ "$HELP" == "true" ]; then
   echo "Usage:"
   echo ""
   echo "  Displays grid configuration information."
   echo ""
   echo "   show_config [-grid $GRIDS_OPT] [-site $SITES_OPT] [-?]"
   echo ""
   echo "      -grid      Starts the locator in the specified grid. Default: ${GRID_DEFAULT}"
   echo "      -site      Starts the locator in the specified site. Default: ${SITE_DEFAULT}"
   echo ""
   echo "   Default: show_config -grid $GRID_DEFAULT -site $SITE_DEFAULT"
   echo ""
   exit
fi

. ${GRIDS_DIR}/${GRID}/site_${SITE}.sh > /dev/null 2>&1

# locators
# LocatorArray elements:
#    array[0] LocatorNumber
#    array[1] LocatorHost
#    array[2] LocatorPort
#    array[3] JmxRmiPort
#    array[4] JmxHttpPort
LOCATOR_NUM=$SERVER_NUM
setLineArray $GRIDS_DIR/$GRID/locator_${SITE}.sh

LOCATOR_HOST_COUNT=$SERVER_COUNT
LOCATORS=""
PADO_LOCATORS=""
declare -a RMI_URL
declare -a PULSE_HTTP_URL
j=0
for (( i = 1; i <= $LAST_SERVER_NUM; i++ ))
do
   line="${LineArray[$i]}"
   array=($line)
   LOCATOR_NUM=${array[0]}
   if [ "$LOCATOR_NUM" == "" ]; then
      continue;
   fi
   LOCATOR_HOST=${array[1]}
   if [ "$LOCATOR_HOST" == "localhost" ]; then
      LOCATOR_HOST=`hostname`
   fi
   LOCATOR_PORT=${array[2]}
   RMI_PORT=${array[3]}
   HTTP_PORT=${array[4]}
   if [ "$LOCATORS" == "" ]; then
      LOCATORS="$LOCATOR_HOST[${LOCATOR_PORT}]"
   else
      LOCATORS=${LOCATORS}",$LOCATOR_HOST[${LOCATOR_PORT}]"
   fi
   if [ "$PADO_LOCATORS" == "" ]; then
      PADO_LOCATORS="$LOCATOR_HOST:${LOCATOR_PORT}"
   else
      PADO_LOCATORS=${PADO_LOCATORS}",$LOCATOR_HOST:${LOCATOR_PORT}"
   fi
   let j=j+1
   RMI_URL[$j]="service:jmx:rmi:///jndi/rmi://${LOCATOR_HOST}:${RMI_PORT}/jmxrmi"
   PULSE_HTTP_URL[$j]="${LOCATOR_HOST}:${HTTP_PORT}/pulse"
done

echo ""
echo "Grid Configuration Summary"
echo "=========================="
echo "Locators"
echo "--------"
echo "                   Grid: $GRID"
echo "                   Site: $SITE"
echo "          Pado Locators: $PADO_LOCATORS"
echo "       GemFire Locators: $LOCATORS"
echo "   Server Debug Enabled: $DEBUG_ENABLED"
echo "        GemFire JMX RMI: ${RMI_URL[1]}"
for (( j = 2; j <= $LOCATOR_HOST_COUNT; j++ ))
do
   echo "                         ${RMI_URL[$j]}"
done
echo "   GemFire Pulse (HTTP): ${PULSE_HTTP_URL[1]}"
for (( j = 2; j <= $LOCATOR_HOST_COUNT; j++ ))
do
   echo "                         ${PULSE_HTTP_URL[$j]}"
done
echo ""

echo "Servers"
echo "-------"

# ServerArray elements:
#   array[0] ServerNumber
#   array[1] ServerHost
#   array[2] ServerPort
#   array[3] DebugPort
#   array[4] JmxPort
#   array[5] IsGateway
setLineArray $GRIDS_DIR/$GRID/server_${SITE}.sh

for (( i = 1; i <= $LAST_SERVER_NUM; i++ ))
do
   line="${LineArray[$i]}"
   array=($line)
   SERVER_NUM=${array[0]}
   if [ "$SERVER_NUM" == "" ]; then
      continue;
   fi
   SERVER_HOST=${array[1]}
   if [ "$SERVER_HOST" == "localhost" ]; then
      SERVER_HOST=`hostname`
   fi
   SERVER_PORT=${array[2]}
   DEBUG_PORT=${array[3]}
   JMX_PORT=${array[4]}
   IS_GATEWAY=${array[5]}
   echo "+ Server #$SERVER_NUM"
   echo "         Host: $SERVER_HOST"
   echo "         Port: $SERVER_PORT"
   echo "          JMX: service:jmx:rmi:///jndi/rmi://${SERVER_HOST}:${JMX_PORT}/jmxrmi"
   echo "   Debug Port: $DEBUG_PORT"
   echo "      Gateway: $IS_GATEWAY"
   echo ""
done
