#!/bin/bash

# ========================================================================
# Copyright (c) 2013-2015 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

. ./setenv.sh > /dev/null 2>&1
. ./all_env.sh > /dev/null 2>&1
. ./argenv.sh > /dev/null 2>&1

if [ "$HELP" == "true" ]; then
   echo "Usage:"
   echo "   start_rpc [-num <server number>] [-grid $GRIDS_OPT] [-site $SITES_OPT] [-?]"
   echo ""
   echo "  Starts RPC agents in the specified grid and site. This command remotely executes"
   echo "  start_rpc. It looks up the remote rpc host mapped by the specified server"
   echo "  number in ${GRIDS_DIR}/${GRID}/rpc_${SITE}.sh"
   echo ""
   echo "      <server number> Server number 1-99"
   echo "      -grid      Starts the agents in the specified grid. Default: ${GRID_DEFAULT}"
   echo "      -site      Starts the agents in the specified site. Default: ${SITE_DEFAULT}"
   echo ""
   echo "   Default: start_rpc -num 1 -grid $GRID_DEFAULT -site $SITE_DEFAULT"
   echo ""
   exit
fi

. ${GRIDS_DIR}/${GRID}/site_${SITE}.sh > /dev/null 2>&1

#
# Target host
#
# RpcArray elements:
#   array[0] ServerNumber
#   array[1] RpcHost
#   array[2] MqttUrl
#   array[3] DebugPort
#   array[4] JmxPort
#   array[5] IsRpcStart
setLineArray $GRIDS_DIR/$GRID/rpc_${SITE}.sh
line="${LineArray[$SERVER_NUM_NO_LEADING_ZERO]}"
array=($line)
RPC_HOST=${array[1]}

if [ "$RPC_HOST" == "" ]; then
i   RPC_HOST=localhost
else
   ssh -q -n $SSH_USER@$RPC_HOST "cd $REMOTE_BASE_DIR/bin_sh; $COMMAND_PREFIX ./start_rpc_local $*;"
fi
