#!/bin/bash

# ========================================================================
# Copyright (c) 2013-2015 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

. ./setenv.sh > /dev/null 2>&1
. ./all_env.sh > /dev/null 2>&1
. ./argenv.sh > /dev/null 2>&1

if [ "$HELP" == "true" ]; then
   echo "Usage:"
   echo "   stop_locator [-num <locator-number>] [-grid $GRIDS_OPT] [-site $SITES_OPT] [-?]"
   echo ""
   echo "   Stops locator in the specified site of the specified grid."
   echo ""
   echo "      <locator number> Locator number 1-99 ($GRID-$SITE: `getLocatorNumberRange`)"
   echo "      -grid      Stops the locator in the specified grid. Default: $GRID_DEFAULT"
   echo "      -site      Stops the locator in the specified site. Default: $SITE_DEFAULT"
   echo ""
   echo "   Default: stop_locator -num 1 -grid $GRID_DEFAULT -site $SITE_DEFAULT"
   echo ""
   exit
fi

. ${GRIDS_DIR}/${GRID}/site_${SITE}.sh > /dev/null 2>&1

# the parent directory of all servers
if [ "$RUN_DIR" == "" ]; then
   RUN_DIR=$BASE_DIR/run
fi
# directory in which the locator to be stopped
DIR=$RUN_DIR/${LOCATOR_ID}
if [ ! -d $DIR ]; then
  mkdir -p $DIR
fi

pushd $DIR > /dev/null 2>&1
echo gfsh stop locator --dir=$DIR
gfsh stop locator --dir=$DIR > /dev/null 2>&1
popd > /dev/null 2>&1
