#!/bin/bash

# ========================================================================
# Copyright (c) 2013-2015 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

. ./setenv.sh > /dev/null 2>&1
. ./all_env.sh > /dev/null 2>&1
. ./argenv.sh > /dev/null 2>&1

if [ "$HELP" == "true" ]; then
   echo "Usage:"
   echo "   stop_server [-num <server number>] [-grid $GRIDS_OPT] [-site $SITES_OPT] [-?]"
   echo ""
   echo "   Stops a server in the specified grid and site. This is a local command."
   echo "   It must be executed in the host where the server is running. To stop"
   echo "   a remote server, run the stop_server command instead."
   echo ""
   echo "      <server number> Server number 1-99"
   echo "      -grid      Stops the server in the specified grid. Default: ${GRID_DEFAULT}"
   echo "      -site      Stops the server in the specified site. Default: ${SITE_DEFAULT}"
   echo ""
   echo "   Default: stop_server -num 1 -grid $GRID_DEFAULT -site $SITE_DEFAULT"
   echo ""
   exit
fi

. ${GRIDS_DIR}/${GRID}/site_${SITE}.sh > /dev/null 2>&1

#
# Target host
#
# ServerArray elements:
#   array[0] ServerNumber
#   array[1] ServerHost
#   array[2] ServerPort
#   array[3] DebugPort
#   array[4] JmxPort
setLineArray $GRIDS_DIR/$GRID/server_${SITE}.sh
line="${LineArray[$SERVER_NUM_NO_LEADING_ZERO]}"
array=($line)
SERVER_ADDRESS=${array[1]}

if [ "$SERVER_ADDRESS" == "" ]; then
   echo "Invalid server number. Please enter the server number and its host address in"
   echo "   ${GRIDS_DIR}/${GRID}/server_${SITE}.sh"
   echo ""
else
   ssh -q -n $SSH_USER@$SERVER_ADDRESS "cd $REMOTE_BASE_DIR/bin_sh; $COMMAND_PREFIX ./stop_server_local $*;"
fi
