#!/bin/bash

# ========================================================================
# Copyright (c) 2013-2017 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

. ./setenv.sh > /dev/null 2>&1

if [ "$HELP" == "true" ]; then
   echo "Usage:"
   echo "   kill_rpc_agent <server-id> [-?]"
   echo ""
   echo "   Default: kill_rpc_agent <server-id mandatory>"
   echo ""
   exit
fi

LANG=java
START_RPC_AGENT="com.netcrest.pado.rpc.client.RpcAgent $*"
pids=`ps -ewwwo pid,comm,args | grep "$START_RPC_AGENT" | grep $LANG | awk '{print $1}'`
for i in $pids; do
   if [ "$agents" == "" ]; then
      agents=$i
   else
      agents="$agents $i"
   fi
done
if [ "$agents" != "" ]; then
   kill -9 $agents
   echo "$LANG: killed [$agents]"
else
   echo "$LANG: rpc agent not running"
fi
