:: ========================================================================
:: Copyright (c) 2013-2017 Netcrest Technologies, LLC. All rights reserved.
::
:: Licensed under the Apache License, Version 2.0 (the "License");
:: you may not use this file except in compliance with the License.
:: You may obtain a copy of the License at
::
::     http://www.apache.org/licenses/LICENSE-2.0
::
:: Unless required by applicable law or agreed to in writing, software
:: distributed under the License is distributed on an "AS IS" BASIS,
:: WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
:: See the License for the specific language governing permissions and
:: limitations under the License.
:: ========================================================================

@echo off
@setlocal enabledelayedexpansion

@call setenv.bat
@call all_env.bat
@call argenv.bat %*

if "%1" == "-?" (
   echo Usage:
   echo Do NOT run this command while servers are running.
   echo It will remove the log and stats files.
   echo    clean_site [-grid %GRIDS_OPT%] [-site %SITES_OPT%] [-al] [-locators] [-persist] [-clients] [-?]
   echo. 
   echo       -grid      Removes log and stats files generated in the specified grid
   echo                  Default: %GRID_DEFAULT%
   echo       -site      Removes log and stats files generated in the specified site
   echo                  Default: %SITE_DEFAULT%
   echo       -all       Removes all files in the specified grid and site
   echo       -locators  Removes locator files in addition to server files
   echo       -persist   Removes persistent files generated by servers
   echo       -clients   Removes client files
   echo. 
   echo    Default: clean_site -grid %GRID_DEFAULT% -site %SITE_DEFAULT%
   echo. 
   goto stop
)

@call %GRIDS_DIR%\%GRID%\site_%SITE%.bat

if "%ALL%" == "true" (
   @set LOCATORS=true
   @set PERSIST=true
)

@set SERVER_HOSTS=localhost
for %%i in (%SERVER_HOSTS%) do (
   clean -grid %GRID% -site %SITE% %*
)

if "%PERSIST%" == "true" (
   echo Removed grid: %GRID%, site: %SITE%, log, stats, and persistent files
) else (
   echo Removed grid: %GRID%, site: %SITE%, log and stats files
)

:stop
