:: ========================================================================
:: Copyright (c) 2013-2015 Netcrest Technologies, LLC. All rights reserved.
::
:: Licensed under the Apache License, Version 2.0 (the "License");
:: you may not use this file except in compliance with the License.
:: You may obtain a copy of the License at
::
::     http://www.apache.org/licenses/LICENSE-2.0
::
:: Unless required by applicable law or agreed to in writing, software
:: distributed under the License is distributed on an "AS IS" BASIS,
:: WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
:: See the License for the specific language governing permissions and
:: limitations under the License.
:: ========================================================================

@echo off
@setlocal enabledelayedexpansion

@call setenv.bat
@call all_env.bat
@call argenv.bat %*

if "%1" == "-?" (
   echo Usage:
   echo Do NOT run this command while servers are running.
   echo It will remove the log and stats files.
   echo.
   echo    clean_server [-num server-number] [-grid %GRIDS_OPT%] [-site %SITES_OPT%] [-persist] [-?]
   echo        server-number server number 1-99
   echo.
   echo        Cleans up server directories by removing log, stats, other temporary files
   echo        from the specified grid and site.
   echo.
   echo       -grid      Removes log and stats files generated in the specified grid
   echo                  Default: %GRID_DEFAULT%
   echo       -site      Removes log and stats files generated in the specified site
   echo                  Default: %SITE_DEFAULT%
   echo       -persist   Removes persistent files generated by servers
   echo.
   echo    Default: clean_server -num 1 -grid %GRID_DEFAULT% -site %SITE_DEFAULT%
   echo. 
   goto stop
)

@call %GRIDS_DIR%\%GRID%\site_%SITE%.bat

if "%RUN_DIR%" == "" (
   @set RUN_DIR=%BASE_DIR%\run
)
if "%LOG_DIR%" == "" (
   @set LOG_DIR=%BASE_DIR%\log
)
if "%STATS_DIR%" == "" (
   @set STATS_DIR=%BASE_DIR%\stats
)

# locators and agents

if "%LOCATORS%" == "true" (
  rmdir /s /q %RUN_DIR%/%LOCATOR_ID%
)
if "%AGENTS%" == "true" (
   rmdir /s /q %RUN_DIR%\%AGENT_ID%
)
if "%CLIENTS%" == "true" (
   erase /f /q %LOG_DIR%\clien*.log
   erase /f /q %STATS_DIR%\client*.gfs
)

rm -f %LOG_DIR/%GRID%_%SITE%%SERVER_NUM%.log %STATS_DIR%/%GRID%_%SITE%%SERVER_NUM%.gfs
if "%PERSIST" == "true" (
   rmdir /s /q %RUN_DIR%\%SERVER_ID%
)

:stop
